name: mapbox_gl
description: A Flutter plugin for integrating Mapbox Maps inside a Flutter application on Android, iOS and web platfroms.
version: 0.8.0
homepage: https://github.com/revoltgames/neopolis_mapbox

dependencies:
  flutter:
    sdk: flutter
  mapbox_gl_platform_interface:
    git:
      url: https://github.com/revoltgames/neopolis_mapbox
      ref: feature/adapte_plugin_for_neopolis
      path: mapbox_gl_platform_interface

flutter:
  plugin:
    platforms:
      android:
        package: com.mapbox.mapboxgl
        pluginClass: MapboxMapsPlugin
      ios:
        pluginClass: MapboxMapsPlugin

environment:
  sdk: ">=2.1.0 <3.0.0"
  # Flutter versions prior to 1.10 did not support the flutter.plugin.platforms map.
  flutter: ">=1.10.0 <2.0.0"
