name: mapbox_gl_web
description: Web platform implementation of mapbox_gl_web
version: 0.1.0
author: 
homepage:

flutter:
  plugin:
    platforms:
      web:
        pluginClass: MapboxMapPlugin
        fileName: mapbox_gl_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  meta: ^1.1.7
  mapbox_gl_platform_interface: 
    path: ../mapbox_gl_platform_interface
  mapbox_gl_dart: ^0.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.4 <2.0.0"