name: Flutter CI

on: [pull_request]

jobs:
  lint:
    name: "Static code analysis"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
    - run: flutter pub get
    - name: Lint analysis
      run: cd example && flutter analyze
      
  check-dart-formatting:
    name: "Check Dart formatting"
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
    - name: Check Dart formatting 
      run: flutter format --set-exit-if-changed .

  check-swift-formatting:
    name: "Check Swift formatting"
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: get SwiftFormat
      run: wget https://github.com/nicklockwood/SwiftFormat/releases/download/0.48.18/swiftformat_linux.zip
    - run: unzip swiftformat_linux.zip
    - run: chmod +x swiftformat_linux
    - name: Check Swift formatting 
      run: ./swiftformat_linux --swiftversion 4.2 --maxwidth 100 --lint ios
    
  build-android:
    environment: ANDROID_CI_DOWNLOADS_TOKEN
    name: "Build Android apk"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
    - run: flutter pub get
    - name: Build example APK
      run: cd example && flutter build apk
      env:
        SDK_REGISTRY_TOKEN: ${{ secrets.SDK_REGISTRY_ANDROID}}

  build-iOS:
    environment: ANDROID_CI_DOWNLOADS_TOKEN
    name: Build iOS package
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
      - run: flutter pub get
      - name: build iOS package
        run: |
          echo "machine api.mapbox.com
          login mapbox
          password $SDK_REGISTRY_TOKEN" >> ~/.netrc
          chmod 600 ~/.netrc
          cd ./example
          flutter build ios --release --no-codesign
        env:
          SDK_REGISTRY_TOKEN: ${{ secrets.SDK_REGISTRY_IOS}}

  build-web:
    name: "Build web"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
    - run: flutter config --enable-web
    - run: flutter pub get
    - name: Build web
      run: cd example && flutter build web
